// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgYCKmDOpAFaT7bXG-bvn6Ckj6OvWbzvQ',
    appId: '1:106308782343:web:130031916dc455ad379da2',
    messagingSenderId: '106308782343',
    projectId: 'hoop-stat',
    authDomain: 'hoop-stat.firebaseapp.com',
    storageBucket: 'hoop-stat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlk8caUhYeaWLtMXIDEwI3ujSANXJvfCA',
    appId: '1:106308782343:android:cc167259e1be63ec379da2',
    messagingSenderId: '106308782343',
    projectId: 'hoop-stat',
    storageBucket: 'hoop-stat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJlr1ujOE3-29n0IxZNcM4F8L0sXiAhnU',
    appId: '1:106308782343:ios:b7912563eb70f15c379da2',
    messagingSenderId: '106308782343',
    projectId: 'hoop-stat',
    storageBucket: 'hoop-stat.appspot.com',
    iosClientId: '106308782343-2tviol8r3peclbou3g8nfub8gggqpa49.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
